### ISSUE TITLE
Maximize icon?

### ISSUE THREAD

**Issue by moso** [UbuntuBudgie/pocillo-gtk-theme#1]
Hey guys,

I'm trying to create a plugin for [hyper](https://github.com/zeit/hyper) that mimics the Pocillo window controls. [I created one](https://github.com/moso/hyper-arc-dark-controls) for Arc Dark last year, but since Budgie is my main distrubuition and want to continue to use it with 18.04, I thought I'd create a Pocillo version.

However, I can't seem to find the correct maximize svg icon anywhere.

When you install the latest 18.04 (2018-03-06) the window controls looks like the image below. However, the "maximize.svg" and "unmaximize.svg" icons in this repo are squares, much of the resemblance of good ol' Numix ([example](https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/master/src/metacity-1/maximize.svg)). And just to clarify: I'm looking for the middle icon:

![screenshot](https://cloud.moso.io/s/7rCpFwej8eXny5o/preview)

I've looked in all theme folders in `/usr/share/theme` and all icon folders in `/usr/share/icons` but I can't seem to find that particular svg pair. Any suggestions?

Thank you for a lovely theme though!

**Comment by fossfreedom** [comment]
that is actually from the icon theme that is being used.

So in this case - Pocillo uses its own icons + Moka + Faba.

The window maximize and minimize icons are here
https://github.com/snwh/faba-icon-theme/tree/master/Faba/symbolic/actions

**Comment by moso** [comment]
Thanks!
