### ISSUE TITLE
Pocillo Gtk.STYLE_CLASS_SUGGESTED_ACTION Color does not match theme

### ISSUE THREAD

**Issue by Jacob-Vlijm** [UbuntuBudgie/pocillo-gtk-theme#11]
In Pocillo, Gtk.STYLE_CLASS_SUGGESTED_ACTION color does not match anything else in the theme, making it pretty ugly when used. Compare e.g. Arc, where it perfectly matches the selected color.

![afbeelding](https://user-images.githubusercontent.com/8932980/49792685-a351b300-fd33-11e8-9c5b-c98eb5327a55.png)

![afbeelding](https://user-images.githubusercontent.com/8932980/49792842-02afc300-fd34-11e8-9028-05966fbdb36c.png)

**Comment by fossfreedom** [comment]
Suggested colour is set here https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/master/src/gtk-3.0/3.22/sass/_colors.scss

**Comment by fossfreedom** [comment]
![ubuntu budgie - new development bionic running - oracle vm virtualbox 1_104](https://user-images.githubusercontent.com/996240/50643751-d704af00-0f66-11e9-9c8c-392a7a0cd06d.png)
