### ISSUE TITLE
Button Colour misleading 

### ISSUE THREAD

**Issue by tomasnorre** [UbuntuBudgie/pocillo-gtk-theme#24]
I have experience today that the button colour tricked me to think that is was unsuccessful. 
Perhaps a better choice of colour would be beneficial. 

The screenshot is from MySQL Workbench when I test my connection before saving it. 

What do you think? I would be happy to help improve this, but would like input first, as it would limit the iterations until something is "accepted". 

![connections_succesful_button](https://user-images.githubusercontent.com/1212481/82650230-af28f080-9c1a-11ea-967c-2e07edf02e8a.png)

**Comment by fossfreedom** [comment]
Red means stop... oops!

Green means success usually - but some people just like a standard button blue.  Guess play to see what's best.

**Comment by tomasnorre** [comment]
I know what the colours normally mean, not sure if the application sends any data that tells me if it ok or not, will check what I can figure out. 

Thanks for a super fast reply.

**Comment by fossfreedom** [comment]
Think this should now be resolved in the rewrite (hopefully)
