### ISSUE TITLE
Does not build with latest inkscape

### ISSUE THREAD

**Issue by gsbhasin123** [UbuntuBudgie/pocillo-gtk-theme#25]
Keep getting these errors:
```
unknown option --export-png=whatever
```
Inkscape has reworked it's CLI. https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line

**Comment by fossfreedom** [comment]
Will look at this in the next few months for ubuntu 20.10.

Might just drop inkscape for resvg

Happy to receive pull requests to resolve sooner

**Comment by gsbhasin123** [comment]
I understand, but people outside ubuntu (I'm currently on solus kde) might want to use it too. Trying a fix.

**Comment by gsbhasin123** [comment]
So i got this: https://hastebin.com/kiloyufayo.bash
building successfully so far. if it ends up working, i'll submit a pr.

**Comment by gsbhasin123** [comment]
It works. Will submit PR soon

**Comment by gsbhasin123** [comment]
Thanks! 
Sorry, was a bit showered with work and completely forgot about this
