### ISSUE TITLE
[UB 20.10] Firefox menu bar transparent gap

### ISSUE THREAD

**Issue by dblueman** [UbuntuBudgie/pocillo-gtk-theme#27]
On Ubuntu Budgie 20.10 with any of the 6 Pocillo theme choices, on my 15.6" 4K Dell XPS laptop, there is a consistent 1 pixel transparent gap underneath the Firefox menu bar:
![budgie-bug2](https://user-images.githubusercontent.com/2580948/98457688-e4ea7300-2181-11eb-9cfa-a230b270abea.png)
Scaled up for easier viewing:
![budgie-bug3](https://user-images.githubusercontent.com/2580948/98457717-267b1e00-2182-11eb-80f3-c2ccdc397e36.png)

This doesn't occur on any of the other supplied themes, so does appear to be an issue with Pocillo. As I'm not familiar with which elements are involved, can someone point me at what changes I can test?

**Comment by fossfreedom** [comment]
firefox theming is here https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/fe3876155e192a1d70e87c4be1576c85a1e22174/src/gtk-3.0/3.22/sass/apps/_third-party.scss#L56

**Comment by fossfreedom** [comment]
@dblueman I've looked at both 200% HiDPI and standard resolutions and cannot reproduce your issue here on both 20.04 and 20.10

Do please check a clean firefox profile to see if its an extension issue.

Also do check with Pocillo icon theme as well since I can see you are using a different icon-theme.

**Comment by dblueman** [comment]
I booted the Ubuntu Budgie 20.10 install stick and also couldn't reproduce it with my settings. 

The issue does reproduce even if I create a totally new user account, so looks like it is an installed package is altering affecting the appearance. I'll investigate the SCSS.

**Comment by fossfreedom** [comment]
@dblueman that commit should hopefully resolve this issue.

**Comment by dblueman** [comment]
Perfect! I built master, installed and reloaded; the issue is resolved nicely.

**Comment by fossfreedom** [comment]
excellent.  I'll backport this to 20.10 & 20.04 soonish.

Please run `ubuntu-bug ubuntu-budgie-themes` to report the issue to
launchpad - then I'll have something to reference as part of the updated
package release.

**Comment by dblueman** [comment]
Superb! Logged it at:
https://bugs.launchpad.net/ubuntu/+source/budgie-artwork/+bug/1905118
