### ISSUE TITLE
[UB 20.10] Cannot select text from edge

### ISSUE THREAD

**Issue by dblueman** [UbuntuBudgie/pocillo-gtk-theme#28]
In Ubuntu Budgie 20.10 with any of the Pocillo theme variants, when an application (eg Gnome-terminal or Gedit) is maximised there is a window border at the left preventing selecting text from the edge.

The Yaru theme for example doesn't have this 1-2 pixels border at the left when applications are maximised, therefore allowing selection of text from the left edge of the screen, improving usability.

It would be great if someone could check if this can be adjusted.

**Comment by fossfreedom** [comment]
I can't reproduce this - but the theme has been rewritten anyway - so hopefully now resolved
