### ISSUE TITLE
QT Apps don't look consistant

### ISSUE THREAD

**Issue by kp2401075** [UbuntuBudgie/pocillo-gtk-theme#36]
It doesn't happen with other themes.

**Reporter Info**
- Pocillo version: Impish Indri ( pre-release version)
- GTK3 version: 3.24.29
- Distribution (and version): Solus 4.2
- Related application (and version): Keepassx(latest), Virtual Box(latest)

**Actual Issue**

Qt apps (using gtk2 theme) look inconsistent with rest. If you are already familiar with issue and working on it, then sorry for reporting it.

![pocillo_issue](https://user-images.githubusercontent.com/20717654/124201970-bbb99100-db1c-11eb-9890-5a097792470d.png)

**Steps to Reproduce**
1. Apply Pocillo gtk theme ( dark or light) from budgie settings.
 

**Additional Info**
Theme was downloaded from github directly was not compiled from source.

**Comment by fossfreedom** [comment]
GTK2 is dead - no one should be using GTK2 based apps - let alone trying to theme via the dead GTK2 plugin.
