### ISSUE TITLE
Notification close button not visible

### ISSUE THREAD

**Issue by algent-al** [UbuntuBudgie/pocillo-gtk-theme#41]
**Reporter Info**

- Pocillo version: 0.9
- GTK3 version: 3.24.33
- Distribution (and version): Solus Budgie 4.3
- Related application (and version): notifications

**Notification close button not visible**

Pocillo theme
![invisible-close-button](https://user-images.githubusercontent.com/46356616/188235109-d279d515-5646-4f4d-a496-5a8e9286dc6f.png)

Materia
![materia](https://user-images.githubusercontent.com/46356616/188235209-b0bedc98-0955-4d64-ab0a-557ca84e8b2c.png)

Qogir
![qogir](https://user-images.githubusercontent.com/46356616/188235234-3e38ded2-18b9-49ea-b1b9-69178c081b59.png)

The close button is visible when hovering the mouse on the notification where the close button is.
![mouse-hover](https://user-images.githubusercontent.com/46356616/188235741-0e6e007c-161e-43aa-9315-4d787e2203ad.png)

**Comment by fossfreedom** [comment]
@algent-al think the above resolves this - please let me know.

**Comment by algent-al** [comment]
Yes, issue resolved thanks.
