### ISSUE TITLE
Styling nautilus files

### ISSUE THREAD

**Issue by theCalcaholic** [UbuntuBudgie/pocillo-gtk-theme#5]
I'm currently trying to add a different background to any other element of lists and I found the correct css classes for basically all lists except the files-view in nautilus. Unfortunately that's the single one case where this theming is most useful, so I was wondering if anyone could tell me which classes need to be used for changing the background-color of a row in the nautilus files-view.

Any help is appreciated. :)

**Comment by fossfreedom** [comment]
You can use gtk inspector to look at the css elements for any app

https://wiki.gnome.org/Projects/GTK%2B/Inspector

So use GTK_DEBUG=interactive nautilus

This will launch both the inspector and nautilus

It is a bit fiddly but you need to navigate down to the nautilus rows and look at the style properties column. Once you have found the nearest style class you can then change the CSS.

**Comment by theCalcaholic** [comment]
Thank you for the response. I tried that already, but the inspector shows me the files list (which is a GtkTreeView) as one, single element and I can't select a row/single file.

Should I be able to do that?

**Comment by fossfreedom** [comment]
To be honest - I don't know.

I suppose dig around some GTK3 themes and see if you can find a theme that currently does this and then can look at the CSS.

I'm aware that xfce thunar GTK2 has this ability - but I've never really seen this with Nauticus GTK+3.  No idea if XFCE Thunar GTK+2 used a treeview or some other GTK+2 widget.
