### ISSUE TITLE
Wrong color of menu bar font

### ISSUE THREAD

**Issue by Hetox** [UbuntuBudgie/pocillo-gtk-theme#7]
Hi!
I like pocillo theme, but after gnome-shell update to version 3.28.3 color of font got too dark
![image](https://user-images.githubusercontent.com/38840184/48980265-83da4980-f0e8-11e8-903a-fa698b9942ca.png)
![image](https://user-images.githubusercontent.com/38840184/48980267-918fcf00-f0e8-11e8-8fbd-cd3b1abc437b.png)
![image](https://user-images.githubusercontent.com/38840184/48980289-bbe18c80-f0e8-11e8-87ae-3f008d3a3c4a.png)

I use pocillo-slim version

**Comment by fossfreedom** [comment]
Hi - the only supported DE is budgie-desktop (README)

If this is reproducible in budgie-desktop please let us know.  Otherwise, any pull-requests to resolve issues for other desktop environments would be gratefully received.  

Thanks.
