### ISSUE TITLE
Inkscape Theme error while using Pocillo-dark-slim

### ISSUE THREAD

**Issue by nikuzin** [UbuntuBudgie/pocillo-gtk-theme#8]
![image](https://user-images.githubusercontent.com/33275794/49011512-de36e100-f1a0-11e8-8012-4c38eeaa9e9c.png)

Only this version of the theme causes error .

**Comment by fossfreedom** [comment]
Is this the deb version of inkscape you are running - or the snap version of inkscape ?

**Comment by nikuzin** [comment]
> Is this the deb version of inkscape you are running - or the snap version of inkscape ?

deb

**Comment by fossfreedom** [comment]
I cannot reproduce this issue on cosmic.

I purge budgie-themes and reinstalled and selected each of the Pocillo themes in turn.  All appeared ok in inkscape.
